spring.application.name=backend
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.time-zone=Europe/Madrid

sendgrid.api-key=${SENDGRID_API_KEY}
sendgrid.from-email=${SENDGRID_FROM_EMAIL:arescaballero96@hotmail.com}

app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000}