spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-stacktrace=always
server.error.include-message=always

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

app.cors.allowed-origins=http://localhost:3000,http://localhost:8081,http://10.0.2.2:8080
