spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.error.include-stacktrace=never
server.error.include-message=never

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
