spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

server.error.include-stacktrace=never
server.error.include-message=never

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
